---
title: "Collaborator Analysis"
format: html
author: SalOehl
---

## Exercise: Explore, Clean, and Wrangle Data
```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```

Read in data

```{r}
lobster_traps <- read_csv("../data/Lobster_Trap_Counts_All_Years_20210519.csv")
```

Explore data
```{r}
head(lobster_traps)
```
```{r}
str(lobster_traps)
```

# Convert missing values

```{r}
traps_clean <- lobster_traps %>%
    mutate(TRAPS = na_if(TRAPS, -99999))

which(is.na(traps_clean$TRAPS))
unique(traps_clean$TRAPS)
```

# Filter practice

```{r}
traps_clean_subset <- traps_clean %>% 
  filter(SITE != "NAPL")

traps_clean_subset2 <- traps_clean %>% 
  filter(SITE == "CARP",
         TRAPS > 20)

max_traps <- traps_clean %>% 
  group_by(SITE, MONTH) %>%
    summarize(max = max(TRAPS, na.rm = TRUE))
```

## Exercise: Data Visualization

```{r}
traps_vis <- traps_clean %>% 
  group_by(YEAR)

ggplot(traps_vis,
       aes(x = TRAPS)) +
    geom_histogram() +
    facet_wrap( ~ YEAR)
```

```{r}
traps_site <- traps_clean %>% 
  group_by(SITE, YEAR) %>% 
  summarize(TRAPS, TOTAL_TRAPS = sum(TRAPS, na.rm = TRUE))

ggplot(traps_site,
  aes(x = YEAR, y = TRAPS, color = SITE)) +
  geom_line() +
  geom_point()
```