---
title: "Owner Analysis"
format: html

author: Evelyn
---

## Exercise: Explore, Clean, and Wrangle Data

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```
```{r}
lobster_abundance <- read_csv("../data/Lobster_Abundance_All_Years_20220829.csv")
```

```{r}
str(lobster_abundance)
```

## 11.2 Convert missing values

```{r}
unique(lobster_abundance$SIZE_MM)
```

```{r}
lobster_abundance <- lobster_abundance %>%
  mutate(SIZE_MM = na_if(SIZE_MM, -99999.0))

unique(lobster_abundance$SIZE_MM)
```

## filter()

```{r}
lobster_abundance_subset <- lobster_abundance %>%
  filter(SITE != "NAPL")

```

```{r}
lobster_abundance_subset2 <- lobster_abundance %>%
  filter( SITE == "AQUE"|SIZE_MM > 70)
```

```{r}
lobster_abundance %>% 

  group_by(SITE, MONTH) %>% 

  summarize(max_value = max(SIZE_MM, na.rm = TRUE)) 
```

## Exercise: Data Visualization

```{r}
ggplot(data = lobster_abundance, 
       aes(x = SIZE_MM)) +
    geom_histogram() +
    facet_wrap(~SITE)
```

```{r}
lobsters_summarize <- lobster_abundance %>% 
  group_by(SITE, YEAR) %>% 
  summarize(COUNT = n())

# line and point plot
ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_point(aes(color = SITE)) +
  geom_line(aes(color = SITE)) +
  labs(x= "Year", y = "Count")
  theme_minimal()


```

```{r}
lobster_size_lrg <- lobster_abundance %>%
    filter(YEAR %in% c(2019, 2020, 2021)) %>%
    mutate(SIZE_BIN = if_else(SIZE_MM <= 70, true = "small", false = "large")) %>%
    group_by(SITE, SIZE_BIN) %>%
    summarize(COUNT = n()) %>%
    drop_na()


```
```{r}
# dodged bar plot
ggplot(data = lobster_size_lrg, aes(x = SITE, y = COUNT, fill = SIZE_BIN)) +
    geom_col(position = "dodge") +
  labs(x= "Site", y = "Count")+
  theme_minimal()
```

